<?php

namespace App\Actions\Version;

use App\Models\Version;

/**
 * Creates a version from validated attributes. Small, synchronous operation:
 * no queue. The uuid is generated by the model; status defaults to draft.
 */
class CreateVersionAction
{
    /**
     * @param array<string, mixed> $attributes
     */
    public function execute(array $attributes): Version
    {
        $attributes['status'] = $attributes['status'] ?? Version::STATUS_DRAFT;

        return Version::create($attributes);
    }
}
